export default {
  REDDIT_FAILURE: 'REDDIT_FAILURE',
  REDDIT_SUCCESS: 'REDDIT_SUCCESS',
  FETCH_REDDIT: 'FETCH_REDDIT',
  HACKERNOON_SUCCESS: 'HACKERNOON_SUCCESS',
  HACKERNOON_FAILURE: 'HACKERNOON_FAILURE',
  HACKERNEWS_SUCCESS: 'HACKERNEWS_SUCCESS',
  HACKERNEWS_FAILURE: 'HACKERNEWS_FAILURE',
  REDIRECT: 'REDIRECT'
};
